/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MyBucket": {
      "endpoint": string
      "name": string
      "type": "sst-scaleway.index.Bucket"
    }
    "MyFunction": {
      "name": string
      "type": "sst-scaleway.index.Function"
      "url": string
    }
  }
}

import "sst"
export {}