/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MyBucket": {
      "endpoint": string
      "name": string
      "type": "sst-scaleway.index.Bucket"
    }
    "MyDatabase": {
      "database": string
      "endpoint": string
      "host": string
      "port": number
      "type": "sst-scaleway.index.Postgres"
    }
    "MyFunction": {
      "name": string
      "type": "sst-scaleway.index.Function"
      "url": string
    }
    "MyQueue": {
      "accessKey": string
      "endpoint": string
      "region": string
      "secretKey": string
      "type": "sst-scaleway.index.Queue"
      "url": string
    }
  }
}

import "sst"
export {}